### ISSUE TITLE
haploDraw

### ISSUE THREAD

**Issue by thoree** [magnusdv/ibdsim2#13]
I need to remove (change?) the `pos` argument to see the colorinG
``` r
library(ribd)
#> Loading required package: pedtools
library(ibdsim2)
x = avuncularPed("u", "ni") |> addSon(parents = c(3,6))
sims = ibdsim(x, N = 1, ids = 3, seed = 123, verbose = F)
s = sims[[1]]
haploDraw(x, s, chrom = 1, cols = 2:7, pos = 2, 
          height = 5, margin = c(2,1,1,1),ids = 3)
```

![](https://i.imgur.com/xebQT36.png)

<sup>Created on 2022-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by magnusdv** [comment]
The problem here is that the haplotypes were drawn outside the margins.

As of e2fd834 the margins are adjusted automatically, so this should be ok now. For example:

``` r
library(ibdsim2, quietly = T)

x = avuncularPed("u", "ni") |> 
  addSon(parents = c(3,6))
sims = ibdsim(x, N = 1, seed = 123, verbose = F)

# Default position: Below
haploDraw(x, sims, chrom = 1, cols = 2:7)
```

![](https://i.imgur.com/lJr25Tp.png)

``` r
# Better positions
haploDraw(x, sims, chrom = 1, cols = 2:7, pos = c(2,4,1,1,1,1,2))
```

![](https://i.imgur.com/kEQC6Q5.png)

<sup>Created on 2022-12-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
