### ISSUE TITLE
Labels/annotation in `haploDraw()`?

### ISSUE THREAD

**Issue by mikldk** [magnusdv/ibdsim2#16]
Is it possible to add labels to `haploDraw()`? Below they are shown in pedigree plot, but not in `haploDraw()`. Maybe it can be done better via `.pedAnnotation()` with e.g. `textInside`, but I couldn't figure out how to do it.

``` r
library(ibdsim2)
#> Indlæser krævet pakke: pedtools
x <- nuclearPed(2)
labs <- c("1" = "Dad", 
          "2" = "Mom",
          "3" = "Boy1",
          "4" = "Boy2")
x <- relabel(x, new = labs)
plot(x)
```

![](https://i.imgur.com/57PxoYc.png)

``` r
chr1 <- loadMap("decode19", chrom = 1)
set.seed(2)
sim <- ibdsim(x, N = 1, map = chr1, verbose = FALSE)
haploDraw(x, sim, unit = "cm", pos = c(2, 4, 2, 4))
```

![](https://i.imgur.com/8sJUkEW.png)

<sup>Created on 2024-07-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by magnusdv** [comment]
Yes, the normal labels are indeed disabled in `haploDraw()` because they usually interfere with the haplotype rectangles. 
However, you can add them with `textAnnot`:
``` r
library(ibdsim2, quietly = T)

x <- nuclearPed(fa = "Dad", mo = "Mom", ch = c("Boy1", "Boy2"))
chr1 <- loadMap("decode19", chrom = 1)
sim <- ibdsim(x, N = 1, map = chr1, seed = 2, verbose = F)

haploDraw(x, sim, unit = "cm", pos = c(2, 4, 2, 4), textAnnot = list(bottom = x$ID))
```
<img src="https://i.imgur.com/cietGpO.png" width="50%" />

Check out the help page `?plotmethods` for more info on `textAnnot`. It is quite flexible! Here is another quick example:
``` r
txt <- list(bottom = x$ID,
           inside = LETTERS[1:4],
           topright = list(1:4, cex = 0.8, col = "red", font = 2, offset = 0.1),
           top = list(c(Boy1 = "comment"), cex = 1.5, col = "green", offset = 3, srt = 20))

haploDraw(x, sim, unit = "cm", pos = c(2, 4, 2, 4), textAnnot = txt)
```
<img src="https://i.imgur.com/cJuMvHu.png" width="50%" />

<sup>Created on 2024-07-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mikldk** [comment]
Thanks, @magnusdv ! Just what I needed.
