### ISSUE TITLE
karyo_diploid

### ISSUE THREAD

**Issue by thoree** [magnusdv/ibdsim2#2]
karyo_diploid understandably fails below , but could respond differently.
The below works for cou = cousinPed(0) but all chromosomes are then shown,
not only the requested 1 and 2.  
``` r
library(pedtools)
library(ibdsim2)
library(ggplot2)
cou = cousinPed(1)
cousins = leaves(cou)
s = ibdsim(cou, 1, chromosomes = 1:2, seed=17, verbose = FALSE)
a = alleleSummary(s[[1]], leaves(cou), ibd.status=TRUE)
pat = a[a[,"ibd_pp"] == 1, ]
mat = a[a[,"ibd_mm"] == 1, ]
karyo_diploid(pat, mat, color = c(paternal = "blue", 
                                maternal = "red"),alpha = 0.8)
#> Error in `$<-.data.frame`(`*tmp*`, "fill", value = structure(1L, .Label = "1", class = "factor")): replacement has 1 row, data has 0
```

Created on 2018-08-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by magnusdv** [comment]
Thanks. Empty input should be handled now, fixed in commits 9b684c3 and 35d04f0.

As for chromosome subsets, your choice of chroms 1 and 2 above applies only to the simulation, not the karyogram. But I have added a parameter `chromosomes` to `karyo_diploid()` enabling karyograms with selected chromosomes only.

So in your example above, you can now use the plot command
```r
karyo_diploid(pat, mat, chrom = 1:2)
```
