### ISSUE TITLE
ibdsim and founder_inbreeding

### ISSUE THREAD

**Issue by thoree** [magnusdv/ibdsim2#3]
The below tells me that founder inbreeding is ignored by ibdsim2
and perhaps it should, but could notify user:

``` r
library(pedtools)
library(ibdsim2)
cou = doubleCousins(0,0)  #remove 's'?
founder_inbreeding(cou, founders(cou)) = 1
cousins = leaves(cou)
s = ibdsim(cou, 1, chromosomes = 21, seed = 17, verbose = FALSE)
a = alleleSummary(s[[1]], leaves(cou), ibd.status=TRUE)
a = as.data.frame(a)
all(a$ibd == 2)
#> [1] FALSE
```

Created on 2018-08-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by magnusdv** [comment]
I cannot see a way for `ibdsim()` to work with inbred founders in general. In order to simulate the chromosomes of an inbred individual, you would need the distribution of number and lengths of IBD segments, which is not encoded in the inbreeding coefficient f.

**But**: This problem is not present in the particular case of 100% inbreeding, where the segments simply are the entire chromosomes! I've implemented this in 148e603: inbred founders are now allowed if (and only if) all founders have inbreeding coeff either 0 or 1, An error is raised otherwised. 

Example: Siblings with both parents 100% inbred.
``` r
library(ibdsim2)
library(pedtools)

x = nuclearPed(2)
founder_inbreeding(x, 1:2) = 1
sim = ibdsim(x, sims = 1, verbose = F)

# The sibs should have kappa like MZ twins
k = realised_kappa(sim, id.pair = 3:4)
k$kappa.hat
#> ibd0 ibd1 ibd2 
#>    0    0    1
```

Created on 2018-08-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
