### ISSUE TITLE
plot_ibd1() and summary statistics 

### ISSUE THREAD

**Issue by thoree** [magnusdv/ibdsim2#8]
Regarding #7 and the wish for standard deviation I was thinking about the below
(which you perhaps get more easily in other ways):

``` r
library(ibdsim2, quietly = TRUE)
x1 = linearPed(2)
s1 = ibdsim(x1, sims = 2, verbose = FALSE)
res = plot_ibd1(s1, pairs = list(c(1,5)))
res$data
#>   count  averlen genomeLength relation ibd1_theory
#> 1    20 93.90920     2864.399        1         0.5
#> 2    25 48.74954     2864.399        1         0.5
```

<sup>Created on 2018-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
Ah, I understand what you mean now. 

`plot_ibd1()` returns the plot object created by `ggplot2`. This is basically a large list, including an entry called `data` containing the main data frame on which the plot is based. What you're asking is to piggy-back on this feature, by adding to the plotting data extra columns which will not be used in the plotting... 

Possible, but sounds hackish to me. A better approach would be to factor the code so that the data is generated in a separate function (i.e. outside of `plot_ibd1()`). I think I'll put this on hold for now, though.

`plot_ibd1()` uses `realised_kappa()` to compute the segment distributions. The easiest way to get summary stats on these would be to call this yourself and analyse the output directly:

``` r
realised_kappa(s1, id.pair = c(1,5))
```

In the source code of `plot_ibd1()` you can see how the output is processed to single out the IBD=1 segments.
